In [1]:
import data
import utility as ut

In [5]:
fold, max_fold = 1, 5
for fold in range(1,6):
    data_range_npd = [(0,90), (91,140), (141,289)]#parts of the new ext parkinson dataset to be used
    sp_pd = ut.get_split_ranges(data_range_npd,fold,max_fold)
    r_pd = sp_pd["train"]
    s_pd = sp_pd["val"]
    print("Fold:", fold)
    print("Train chunk:", r_pd)
    print("Valdn chunk:", s_pd)

Fold: 1
Train chunk: [(19, 36), (37, 54), (55, 72), (73, 90), (101, 110), (111, 120), (121, 130), (131, 140), (171, 200), (201, 230), (231, 260), (261, 289)]
Valdn chunk: [(0, 18), (91, 100), (141, 170)]
Fold: 2
Train chunk: [(0, 18), (37, 54), (55, 72), (73, 90), (91, 100), (111, 120), (121, 130), (131, 140), (141, 170), (201, 230), (231, 260), (261, 289)]
Valdn chunk: [(19, 36), (101, 110), (171, 200)]
Fold: 3
Train chunk: [(0, 18), (19, 36), (55, 72), (73, 90), (91, 100), (101, 110), (121, 130), (131, 140), (141, 170), (171, 200), (231, 260), (261, 289)]
Valdn chunk: [(37, 54), (111, 120), (201, 230)]
Fold: 4
Train chunk: [(0, 18), (19, 36), (37, 54), (73, 90), (91, 100), (101, 110), (111, 120), (131, 140), (141, 170), (171, 200), (201, 230), (261, 289)]
Valdn chunk: [(55, 72), (121, 130), (231, 260)]
Fold: 5
Train chunk: [(0, 18), (19, 36), (37, 54), (55, 72), (91, 100), (101, 110), (111, 120), (121, 130), (141, 170), (171, 200), (201, 230), (231, 260)]
Valdn chunk: [(73, 90), (131, 140), (261, 289)]

In [9]:
batch = 10
print(batch)
for batch in range(10):
    print(batch)
print("Batch", batch)

10
0
1
2
3
4
5
6
7
8
9
Batch 9

In [11]:
ut.get_array_info(data.get_newext_dev_parkinson_cls_data()[0], "New EXT Dev Data")

----------
New EXT Dev Data specifications:
<class 'numpy.ndarray'>
(290, 95, 69, 79, 1)
float32
Mean 0.521783
Median 0.448994
Max 2.54515
Min -0.0328023
std.dev. 0.426738
----------

In [16]:
import numpy as np
fq = np.sum(data.get_newext_dev_parkinson_cls_data()[1],axis=0 )
sm = np.sum(fq)
wts = np.square(sm/fq)

In [23]:
wts[:,0]

array([ 10.15577793,  33.6400032 ,   3.78811765], dtype=float32)

In [19]:
wt2 = np.sum(fq*fq)/(fq*fq)
wt2

array([[  3.98285222],
       [ 13.19279957],
       [  1.4856087 ]], dtype=float32)

In [21]:
fq
fq*fq

array([[  8281.],
       [  2500.],
       [ 22201.]], dtype=float32)

In [24]:
import data
import numpy as np

In [51]:
X, Y = data.get_newext_dev_parkinson_cls_data()
Z, = data.get_newext_test_parkinson_cls_data()

In [52]:
ut.get_array_info(X)
ut.get_array_info(Z)

----------
Array specifications:
<class 'numpy.ndarray'>
(290, 95, 69, 79, 1)
float32
Mean 0.521783
Median 0.448994
Max 2.54515
Min -0.0328023
std.dev. 0.426738
----------
----------
Array specifications:
<class 'numpy.ndarray'>
(108, 95, 69, 79, 1)
float32
Mean 0.518901
Median 0.438323
Max 1.84031
Min 0.0
std.dev. 0.425261
----------

In [48]:
X1 = X[0,:,:,:,0]
num_pix_mx = np.where(X>1.84030)
num_pix_mn = np.where(X<0)
print(num_pix_mx[0].shape[0])
print(num_pix_mn[0].shape[0])

1179
10572

In [50]:
X_clipped = np.clip(X, 0,1.84031 )
num_pix_mx = np.where(X_clipped>1.84030)
num_pix_mn = np.where(X_clipped<0)
print(num_pix_mx[0].shape[0])
print(num_pix_mn[0].shape[0])

1179
0

In [53]:
k_fname = 'data_stats/new_extended_blindtest_data_index_volume_key_mapping.txt'
kmap = None
with open(k_fname, 'r') as f:
    kmap = eval(f.read())
print(kmap)

{0: 'sw102376', 1: 'sw102584', 2: 'sw102904', 3: 'sw102930', 4: 'sw103512', 5: 'sw103753', 6: 'sw104538', 7: 'sw105890', 8: 'sw106184', 9: 'sw106576', 10: 'sw106856', 11: 'sw109624', 12: 'sw110208', 13: 'sw110212', 14: 'sw110394', 15: 'sw110728', 16: 'sw110729', 17: 'sw110730', 18: 'sw111188', 19: 'sw111746', 20: 'sw111747', 21: 'sw111767', 22: 'sw111822', 23: 'sw119611', 24: 'sw119890', 25: 'sw120359', 26: 'sw120757', 27: 'sw120901', 28: 'sw121509', 29: 'sw121803', 30: 'sw121820', 31: 'sw121900', 32: 'sw36060', 33: 'sw40772', 34: 'sw45873', 35: 'sw56357', 36: 'sw57759', 37: 'sw59995', 38: 'sw60242', 39: 'sw62207', 40: 'sw63090', 41: 'sw66752', 42: 'sw67516', 43: 'sw67575', 44: 'sw68171', 45: 'sw68172', 46: 'sw69063', 47: 'sw69356', 48: 'sw70579', 49: 'sw70628', 50: 'sw71143', 51: 'sw71408', 52: 'sw72425', 53: 'sw73612', 54: 'sw73768', 55: 'sw74159', 56: 'sw75549', 57: 'sw77593', 58: 'sw79859', 59: 'sw81013', 60: 'sw82079', 61: 'sw82243', 62: 'sw82440', 63: 'sw82443', 64: 'sw82444', 65: 'sw84568', 66: 'sw84692', 67: 'sw85049', 68: 'sw85087', 69: 'sw85610', 70: 'sw85611', 71: 'sw86369', 72: 'sw86648', 73: 'sw86770', 74: 'sw87290', 75: 'sw87802', 76: 'sw87904', 77: 'sw88153', 78: 'sw89092', 79: 'sw89167', 80: 'sw89755', 81: 'sw89891', 82: 'sw90544', 83: 'sw90569', 84: 'sw91196', 85: 'sw91246', 86: 'sw91581', 87: 'sw92487', 88: 'sw93507', 89: 'sw93859', 90: 'sw94320', 91: 'sw94888', 92: 'sw94972', 93: 'sw96346', 94: 'sw96807', 95: 'sw97204', 96: 'sw97450', 97: 'sw97499', 98: 'sw97504', 99: 'sw97557', 100: 'sw97606', 101: 'sw97740', 102: 'sw98039', 103: 'sw98888', 104: 'sw99048', 105: 'sw99549', 106: 'sw99808', 107: 'sw99886'}

In [55]:
import imp

In [57]:
imp.reload(data)

In [59]:
ikm = data.get_newext_test_parkinson_cls_data_idx_key_map()

In [60]:
import pandas

In [61]:
amax_preds = np.zeros(shape=(108,1), dtype=np.float32)

In [72]:
amax_preds[36:72] = 1.0
amax_preds[72:] = 2.0

In [74]:
cls_to_name = {0:"MSA", 1:"PSP", 2:"PD"}
for i in range(amax_preds.shape[0]):
    print(cls_to_name[amax_preds[i,0]])

MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
MSA
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PSP
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD
PD

In [73]:
amax_preds

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.],
       [ 2.]], dtype=float32)

In [81]:
pd = pandas
def _get_class_label_list_and_volume_id_as_df(label_id_array, data_index_volume_key_map):
    """Returns a dataframe with three columns VOLUME_ID, LABEL and PREDICTED_CLASS_ID
    VOLUME_ID[i] is taken as data_index_key_map[i], make sure you feed the correct idx-key mapping.
    """
    assert(label_id_array.shape==(108,1))# raising error in case of unintended use(using partial chunks)
    id_to_name = {0:'MSA', 1:'PSP', 2:'PD'}#DO NOT CHANGE
    df_data = []
    for idx in range(label_id_array.shape[0]):
        vid = data_index_volume_key_map[idx]
        pred_cls_id  = label_id_array[idx,0]
        assert(pred_cls_id in [0.0, 1.0, 2.0])
        cls_name = id_to_name[pred_cls_id]
        df_data.append((vid, cls_name, pred_cls_id))
    return pd.DataFrame(data=df_data, columns=['VOLUME_ID', 'LABEL', 'PREDICTED_CLASS_ID'])

In [82]:
pre_df = _get_class_label_list_and_volume_id_as_df(amax_preds, ikm)

In [83]:
pre_df.head()

  VOLUME_ID LABEL  PREDICTED_CLASS_ID
0  sw102376   MSA                 0.0
1  sw102584   MSA                 0.0
2  sw102904   MSA                 0.0
3  sw102930   MSA                 0.0
4  sw103512   MSA                 0.0

In [84]:
pre_df

    VOLUME_ID LABEL  PREDICTED_CLASS_ID
0    sw102376   MSA                 0.0
1    sw102584   MSA                 0.0
2    sw102904   MSA                 0.0
3    sw102930   MSA                 0.0
4    sw103512   MSA                 0.0
5    sw103753   MSA                 0.0
6    sw104538   MSA                 0.0
7    sw105890   MSA                 0.0
8    sw106184   MSA                 0.0
9    sw106576   MSA                 0.0
10   sw106856   MSA                 0.0
11   sw109624   MSA                 0.0
12   sw110208   MSA                 0.0
13   sw110212   MSA                 0.0
14   sw110394   MSA                 0.0
15   sw110728   MSA                 0.0
16   sw110729   MSA                 0.0
17   sw110730   MSA                 0.0
18   sw111188   MSA                 0.0
19   sw111746   MSA                 0.0
20   sw111747   MSA                 0.0
21   sw111767   MSA                 0.0
22   sw111822   MSA                 0.0
23   sw119611   MSA                 0.0
24   sw119890   MSA                 0.0
25   sw120359   MSA                 0.0
26   sw120757   MSA                 0.0
27   sw120901   MSA                 0.0
28   sw121509   MSA                 0.0
29   sw121803   MSA                 0.0
..        ...   ...                 ...
78    sw89092    PD                 2.0
79    sw89167    PD                 2.0
80    sw89755    PD                 2.0
81    sw89891    PD                 2.0
82    sw90544    PD                 2.0
83    sw90569    PD                 2.0
84    sw91196    PD                 2.0
85    sw91246    PD                 2.0
86    sw91581    PD                 2.0
87    sw92487    PD                 2.0
88    sw93507    PD                 2.0
89    sw93859    PD                 2.0
90    sw94320    PD                 2.0
91    sw94888    PD                 2.0
92    sw94972    PD                 2.0
93    sw96346    PD                 2.0
94    sw96807    PD                 2.0
95    sw97204    PD                 2.0
96    sw97450    PD                 2.0
97    sw97499    PD                 2.0
98    sw97504    PD                 2.0
99    sw97557    PD                 2.0
100   sw97606    PD                 2.0
101   sw97740    PD                 2.0
102   sw98039    PD                 2.0
103   sw98888    PD                 2.0
104   sw99048    PD                 2.0
105   sw99549    PD                 2.0
106   sw99808    PD                 2.0
107   sw99886    PD                 2.0

[108 rows x 3 columns]